title: "jimbit.io"
author: "Jimmy van Ameyde"
description: "Created via GitHub pages, Contrast theme for Jekyll."
permalink: /:title/
lang: "en"
excerpt_separator: <!--more-->
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Blog."}
  - {file: "about.md", title: "About.", icon: "code"}
#  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
#  - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/jvameyde"}
  - {title: Github, icon: github, url: "https://github.com/jimbit-io"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
